from pathlib import Path
from html import escape
import re

ROOT=Path('_site')
STYLE='/assets/phase32.css?v=32'
PHONE='+34 600 703 303'
EMAIL='partnership@ibizavipmove.com'
WA='https://wa.me/34600703303'

PAGES={
'es':{
'path':'/es/contacto/','eyebrow':'Private Members Desk · Ibiza','h1':'Cuéntanos qué tiene que ocurrir.','intro':'Comparte lo esencial. Un único contacto privado continuará la conversación y coordinará los siguientes pasos alrededor de tu estancia en Ibiza.','wa':'WhatsApp 24/7','call':'Llamar al concierge','line':'Línea privada','email':'Email','coverage':'Cobertura','coverage_v':'Ibiza · Atención privada','brief':'Brief privado','brief_h':'Empieza por lo esencial.','brief_p':'No necesitas tener todo el itinerario cerrado. Fechas, huéspedes y la necesidad principal son suficientes para empezar.','name':'Nombre','phone':'WhatsApp / Teléfono','arrival':'Llegada','departure':'Salida','service':'Servicio principal','guests':'Huéspedes','details':'Brief privado','placeholder':'Villa, transporte, yate, reservas, vuelos, seguridad, peticiones especiales...','send':'Enviar brief privado','note':'Al enviar se abre una conversación privada de WhatsApp con estos datos. Nada se considera confirmado hasta acordar disponibilidad y condiciones.','trust':[('01 · Un contacto','Todo el brief conectado.','Los servicios confirmados pueden coordinarse bajo una sola línea de comunicación.'),('02 · Gestión privada','Discreción por diseño.','Solo se comparten los detalles operativos necesarios para cada solicitud confirmada.'),('03 · Soporte ágil','Los planes pueden cambiar.','Cuando cambian horarios o necesidades, los elementos afectados pueden realinearse.')], 'options':['Concierge completo','Chófer privado','Villa privada','Yate / Charter','Aviación privada','Restaurantes / Nightlife','Seguridad privada','Chef / Staffing','Wellness','Evento privado','Solicitud a medida']},
'fr':{
'path':'/fr/contact/','eyebrow':'Private Members Desk · Ibiza','h1':'Dites-nous ce qui doit se passer.','intro':'Partagez l’essentiel. Un contact privé poursuivra la conversation et coordonnera les prochaines étapes autour de votre séjour à Ibiza.','wa':'WhatsApp 24/7','call':'Appeler la conciergerie','line':'Ligne privée','email':'Email','coverage':'Zone','coverage_v':'Ibiza · Assistance privée','brief':'Brief privé','brief_h':'Commencez par l’essentiel.','brief_p':'Vous n’avez pas besoin d’un itinéraire complet. Les dates, les invités et la demande principale suffisent pour commencer.','name':'Nom','phone':'WhatsApp / Téléphone','arrival':'Arrivée','departure':'Départ','service':'Service principal','guests':'Invités','details':'Brief privé','placeholder':'Villa, transport, yacht, réservations, vol, sécurité, demandes spéciales...','send':'Envoyer le brief privé','note':'L’envoi ouvre une conversation WhatsApp privée avec ces informations. Rien n’est confirmé avant validation de la disponibilité et des conditions.','trust':[('01 · Un contact','Votre brief reste connecté.','Les services confirmés peuvent être coordonnés via une seule ligne de communication.'),('02 · Gestion privée','La discrétion par conception.','Seuls les détails opérationnels nécessaires sont partagés pour chaque demande confirmée.'),('03 · Support réactif','Les plans peuvent évoluer.','Lorsque les horaires ou besoins changent, les éléments concernés peuvent être réalignés.')], 'options':['Conciergerie complète','Chauffeur privé','Villa privée','Yacht / Charter','Aviation privée','Restaurants / Nightlife','Sécurité privée','Chef / Personnel de villa','Wellness','Événement privé','Demande sur mesure']},
'de':{
'path':'/de/kontakt/','eyebrow':'Private Members Desk · Ibiza','h1':'Sagen Sie uns, was passieren soll.','intro':'Teilen Sie die wichtigsten Angaben. Ein privater Ansprechpartner führt das Gespräch weiter und koordiniert die nächsten Schritte rund um Ihren Ibiza-Aufenthalt.','wa':'WhatsApp 24/7','call':'Concierge anrufen','line':'Private Linie','email':'E-Mail','coverage':'Region','coverage_v':'Ibiza · Private Betreuung','brief':'Privates Briefing','brief_h':'Beginnen Sie mit dem Wesentlichen.','brief_p':'Der gesamte Reiseplan muss noch nicht feststehen. Daten, Gäste und die wichtigste Anforderung reichen für den Start.','name':'Name','phone':'WhatsApp / Telefon','arrival':'Anreise','departure':'Abreise','service':'Hauptservice','guests':'Gäste','details':'Privates Briefing','placeholder':'Villa, Transport, Yacht, Reservierungen, Flug, Security, besondere Wünsche...','send':'Privates Briefing senden','note':'Beim Senden öffnet sich eine private WhatsApp-Unterhaltung mit diesen Angaben. Nichts gilt als bestätigt, bevor Verfügbarkeit und Bedingungen vereinbart sind.','trust':[('01 · Ein Kontakt','Das Briefing bleibt verbunden.','Bestätigte Services können über eine zentrale Kommunikationslinie koordiniert werden.'),('02 · Private Bearbeitung','Diskretion als Standard.','Nur die für eine bestätigte Anfrage notwendigen operativen Details werden geteilt.'),('03 · Reaktive Betreuung','Pläne können sich ändern.','Wenn Zeiten oder Anforderungen wechseln, können betroffene Elemente neu abgestimmt werden.')], 'options':['Full Concierge','Privater Chauffeur','Private Villa','Yacht / Charter','Private Aviation','Restaurants / Nightlife','Private Security','Private Chef / Villa Staff','Wellness','Private Event','Bespoke Request']},
'ar':{
'path':'/ar/contact/','eyebrow':'Private Members Desk · Ibiza','h1':'أخبرنا بما يجب أن يحدث.','intro':'شارك معنا المعلومات الأساسية. سيتابع معك مسؤول خاص واحد المحادثة وينسق الخطوات التالية حول إقامتك في إيبيزا.','wa':'واتساب 24/7','call':'الاتصال بالكونسيرج','line':'خط خاص','email':'البريد الإلكتروني','coverage':'النطاق','coverage_v':'إيبيزا · دعم خاص','brief':'طلب خاص','brief_h':'ابدأ بالمعلومات الأساسية.','brief_p':'لا تحتاج إلى برنامج مكتمل. التواريخ والضيوف والطلب الرئيسي تكفي لبدء التنسيق.','name':'الاسم','phone':'واتساب / الهاتف','arrival':'الوصول','departure':'المغادرة','service':'الخدمة الرئيسية','guests':'الضيوف','details':'تفاصيل الطلب','placeholder':'فيلا، تنقل، يخت، حجوزات، رحلة، أمن، طلبات خاصة...','send':'إرسال الطلب الخاص','note':'عند الإرسال سيتم فتح محادثة واتساب خاصة بهذه المعلومات. لا تعتبر أي خدمة مؤكدة قبل الاتفاق على التوفر والشروط.','trust':[('01 · جهة اتصال واحدة','كل التفاصيل مترابطة.','يمكن تنسيق الخدمات المؤكدة عبر خط تواصل واحد.'),('02 · إدارة خاصة','السرية جزء من التصميم.','يتم مشاركة التفاصيل التشغيلية الضرورية فقط لكل طلب مؤكد.'),('03 · دعم سريع','الخطط قد تتغير.','عند تغير الوقت أو الاحتياجات يمكن إعادة تنسيق العناصر المتأثرة.')], 'options':['كونسيرج كامل','سائق خاص','فيلا خاصة','يخت / تشارتر','طيران خاص','مطاعم / حياة ليلية','أمن خاص','شيف / طاقم فيلا','عافية وجمال','فعالية خاصة','طلب مخصص']}
}


def main(d):
    opts=''.join(f'<option value="{escape(x)}">{escape(x)}</option>' for x in d['options'])
    trust=''.join(f'<article><span>{escape(n)}</span><strong>{escape(h)}</strong><p>{escape(p)}</p></article>' for n,h,p in d['trust'])
    return f'''<main id="main-content"><section class="ivm-desk"><div class="ivm-desk-shell"><div class="ivm-desk-intro"><div class="eyebrow">{escape(d['eyebrow'])}</div><h1>{escape(d['h1'])}</h1><p>{escape(d['intro'])}</p><div class="ivm-desk-actions"><a class="btn gold" href="{WA}">{escape(d['wa'])}</a><a class="btn ghost" href="tel:+34600703303">{escape(d['call'])}</a></div><div class="ivm-desk-meta"><div><span>{escape(d['line'])}</span><a href="tel:+34600703303">{PHONE}</a></div><div><span>{escape(d['email'])}</span><a href="mailto:{EMAIL}">{EMAIL}</a></div><div><span>{escape(d['coverage'])}</span><strong>{escape(d['coverage_v'])}</strong></div></div></div><div class="ivm-desk-form"><div class="ivm-desk-form-head"><div><div class="eyebrow">{escape(d['brief'])}</div><h2>{escape(d['brief_h'])}</h2></div><p>{escape(d['brief_p'])}</p></div><form id="localizedConciergeForm"><label>{escape(d['name'])}<input id="fName" autocomplete="name" required></label><label>{escape(d['phone'])}<input id="fPhone" autocomplete="tel" required></label><label>{escape(d['arrival'])}<input id="fArrival" type="date"></label><label>{escape(d['departure'])}<input id="fDeparture" type="date"></label><label class="full">{escape(d['service'])}<select id="fService">{opts}</select></label><label>{escape(d['guests'])}<input id="fGuests" type="number" min="1" inputmode="numeric"></label><label class="full">{escape(d['details'])}<textarea id="fBrief" rows="4" placeholder="{escape(d['placeholder'])}"></textarea></label><div class="form-submit"><button class="btn dark" type="submit">{escape(d['send'])}</button><small>{escape(d['note'])}</small></div></form></div></div><div class="ivm-desk-trust">{trust}</div></section></main>'''

for lang,d in PAGES.items():
    page=ROOT/d['path'].strip('/')/'index.html'
    if not page.exists(): raise SystemExit(f'Missing localized contact page: {lang}')
    html=page.read_text(encoding='utf-8')
    html,n=re.subn(r'<main\b[^>]*>.*?</main>',main(d),html,count=1,flags=re.I|re.S)
    if n!=1: raise SystemExit(f'Unable to replace localized contact main: {lang}')
    body=re.search(r'<body(?:\s+class="([^"]*)")?>',html,re.I)
    if body:
        classes=(body.group(1) or '').split()
        if 'ivm-private-desk' not in classes: classes.append('ivm-private-desk')
        repl='<body class="'+' '.join(x for x in classes if x)+'">';html=html[:body.start()]+repl+html[body.end():]
    if STYLE not in html: html=html.replace('</head>',f'<link rel="stylesheet" href="{STYLE}"></head>',1)
    page.write_text(html,encoding='utf-8')

for lang,d in PAGES.items():
    html=(ROOT/d['path'].strip('/')/'index.html').read_text(encoding='utf-8')
    assert STYLE in html and 'ivm-private-desk' in html,lang
    assert html.count('<h1')==1,lang
    assert 'id="localizedConciergeForm"' in html,lang
    for field in ('fName','fPhone','fArrival','fDeparture','fService','fGuests','fBrief'): assert f'id="{field}"' in html,(lang,field)
    assert 'id="main-content"' in html and 'ivm-skip-link' in html,lang
    assert '<link rel="canonical"' in html and 'application/ld+json' in html,lang
print('PASS: Phase 39 Private Members Desk applied to ES/FR/DE/AR contact pages')
