from pathlib import Path
import json
import re

ROOT = Path('_site')
STYLE = '/assets/phase45.css?v=45'

COPY = {
'en': {
'chef': [('What information helps when requesting a private chef or villa staffing in Ibiza?','Share the dates, guest count, property location, preferred service style, dietary requirements and any known staffing needs. Confirmed essentials are enough to begin even if menus or schedules are still evolving.'),('Can chef and staffing arrangements be coordinated with the rest of the stay?','Yes. Meal timing, villa access, chauffeur movements, events and guest schedules can be considered together so the household plan remains aligned.'),('What if guest numbers or timings change?','The affected staffing and service windows can be reviewed around the updated information. Early notice is useful because availability and setup requirements may change.'),('Is every chef or staffing request automatically confirmed?','No. Requests remain subject to professional availability, suitability, property conditions and final confirmation. The brief helps identify the right structure before anything is treated as confirmed.')],
'car': [('What should be included in a luxury car rental brief in Ibiza?','Share the dates, preferred vehicle category, driver requirements, delivery and collection points, passenger needs and any known luggage considerations.'),('Can car rental be coordinated with a villa or wider concierge itinerary?','Yes. Vehicle delivery, villa access, chauffeur support and other confirmed services can be aligned around the same stay.'),('What happens if the requested model is unavailable?','Comparable alternatives can be discussed around the client’s priorities. Exact models, specifications and availability are always subject to supplier confirmation.'),('Are rental terms the same for every vehicle?','No. Age, licence, deposit, insurance, mileage and delivery conditions can vary by supplier and vehicle. Final terms must be confirmed before booking.')],
'wellness': [('What information helps when arranging wellness services in Ibiza?','Share the dates, location, number of guests, preferred treatment or practice, timing and any relevant non-sensitive preferences that affect the setup.'),('Can wellness appointments be coordinated at a villa?','Where the provider and property conditions allow it, in-villa appointments can be coordinated around the wider schedule and access requirements.'),('Can wellness plans change during the stay?','Yes, subject to provider availability. Timing or service requests can be reviewed as the itinerary develops.'),('Does concierge wellness coordination replace medical advice?','No. Ibiza VIP Move coordinates hospitality and wellness services only. Medical questions, diagnoses or treatment decisions should be handled by appropriately qualified healthcare professionals.')],
'events': [('What should be included in a private event brief in Ibiza?','Share the date, guest count, location or preferred setting, event style, timing and known requirements such as transport, staffing, security, dining or entertainment.'),('Can transport, security and staffing be coordinated with the event?','Yes. These operational elements can be planned around one event timeline so arrivals, guest movements and service teams work from the same brief.'),('Can an event be planned if some details are still undecided?','Yes. Confirmed anchors such as date, guest count and venue direction are enough to begin shaping the brief while other elements are refined.'),('Are venues, suppliers or permissions guaranteed?','No. Venue access, suppliers, permissions and specialist requirements remain subject to availability, contracts, property rules and any applicable legal or operational approvals.')],
'bespoke': [('What is a bespoke concierge request?','It is a request that does not fit neatly into a single service category and may require several suppliers, locations or operational steps to be coordinated together.'),('What information is useful for a bespoke request?','Share the objective, dates, guest profile, locations, timing, constraints and what has already been confirmed. The clearer the priorities, the easier it is to assess the request.'),('Can several different services be combined into one brief?','Yes. Bespoke coordination is especially useful when transport, property, dining, staffing, security, events or other services need to work as one itinerary.'),('Can every bespoke request be arranged?','No. Requests must be legal, safe, viable and compatible with supplier availability, property rules and local requirements. Nothing is treated as confirmed until the relevant elements are verified.')]
},
'es': {
'chef': [('¿Qué información ayuda al solicitar chef privado o personal de villa en Ibiza?','Comparte fechas, número de huéspedes, ubicación de la propiedad, estilo de servicio, requisitos alimentarios y cualquier necesidad conocida de personal. Los datos esenciales confirmados bastan para empezar.'),('¿Se puede coordinar chef y personal con el resto de la estancia?','Sí. Horarios de comidas, acceso a la villa, chóferes, eventos y agenda de los huéspedes pueden alinearse dentro del mismo planning.'),('¿Qué ocurre si cambian los invitados o los horarios?','Se pueden revisar los turnos y servicios afectados según la nueva información. Avisar con antelación ayuda porque la disponibilidad y la preparación pueden cambiar.'),('¿Toda solicitud de chef o staffing queda confirmada automáticamente?','No. Todo depende de disponibilidad profesional, adecuación al servicio, condiciones de la propiedad y confirmación final.')],
'car': [('¿Qué debería incluir una solicitud de alquiler de coche de lujo en Ibiza?','Fechas, categoría de vehículo, requisitos de conductor, puntos de entrega y recogida, pasajeros y necesidades de equipaje ayudan a definir la solicitud.'),('¿Se puede coordinar el coche con la villa o el resto del concierge?','Sí. Entrega del vehículo, acceso a la villa, apoyo de chófer y otros servicios confirmados pueden alinearse alrededor de la misma estancia.'),('¿Qué ocurre si el modelo solicitado no está disponible?','Se pueden proponer alternativas comparables según las prioridades del cliente. Modelos exactos, especificaciones y disponibilidad dependen siempre de confirmación del proveedor.'),('¿Las condiciones de alquiler son iguales para todos los vehículos?','No. Edad, permiso de conducir, depósito, seguro, kilometraje y condiciones de entrega pueden variar según proveedor y vehículo.')],
'wellness': [('¿Qué información ayuda a organizar servicios wellness en Ibiza?','Comparte fechas, ubicación, número de personas, tratamiento o práctica preferida, horario y cualquier preferencia relevante para la preparación.'),('¿Se pueden coordinar sesiones wellness en una villa?','Cuando el profesional y las condiciones de la propiedad lo permiten, pueden coordinarse sesiones en villa alrededor del resto del planning.'),('¿Se puede modificar el plan wellness durante la estancia?','Sí, sujeto a disponibilidad del profesional. Horarios y servicios pueden revisarse a medida que evoluciona el itinerario.'),('¿La coordinación wellness sustituye asesoramiento médico?','No. Ibiza VIP Move coordina servicios de hospitality y wellness. Las cuestiones médicas, diagnósticos o tratamientos deben tratarse con profesionales sanitarios cualificados.')],
'events': [('¿Qué debería incluir un brief para un evento privado en Ibiza?','Fecha, número de invitados, ubicación o tipo de espacio, estilo del evento, horario y necesidades conocidas de transporte, personal, seguridad, gastronomía o entretenimiento.'),('¿Se pueden coordinar transporte, seguridad y personal con el evento?','Sí. Estos elementos pueden organizarse alrededor de un único timing para que llegadas, movimientos y equipos trabajen con el mismo brief.'),('¿Se puede empezar si aún faltan detalles del evento?','Sí. Fecha, número de invitados y dirección general del venue son suficientes para comenzar mientras se definen otros elementos.'),('¿Están garantizados venues, proveedores o permisos?','No. Acceso, proveedores, permisos y requisitos especiales dependen de disponibilidad, contratos, reglas de la propiedad y autorizaciones aplicables.')],
'bespoke': [('¿Qué es una solicitud de concierge a medida?','Es una petición que no encaja en una sola categoría y puede requerir varios proveedores, ubicaciones o pasos operativos coordinados.'),('¿Qué información es útil para una solicitud bespoke?','Comparte objetivo, fechas, perfil de invitados, ubicaciones, horarios, limitaciones y lo que ya está confirmado.'),('¿Se pueden combinar varios servicios en un mismo brief?','Sí. Es especialmente útil cuando transporte, villa, dining, personal, seguridad, eventos u otros servicios deben funcionar como un único itinerario.'),('¿Se puede organizar cualquier solicitud a medida?','No. Las solicitudes deben ser legales, seguras, viables y compatibles con disponibilidad, reglas de propiedades y requisitos locales. Nada se considera confirmado hasta verificarlo.')]
},
'fr': {
'chef': [('Quelles informations sont utiles pour demander un chef privé ou du personnel de villa à Ibiza ?','Partagez les dates, le nombre d’invités, l’emplacement de la propriété, le style de service, les besoins alimentaires et les besoins connus en personnel.'),('Le chef et le personnel peuvent-ils être coordonnés avec le reste du séjour ?','Oui. Horaires des repas, accès à la villa, chauffeurs, événements et programme des invités peuvent être alignés dans un même planning.'),('Que se passe-t-il si le nombre d’invités ou les horaires changent ?','Les services et créneaux concernés peuvent être réévalués selon les nouvelles informations. Prévenir tôt aide car disponibilité et préparation peuvent évoluer.'),('Toute demande de chef ou de staffing est-elle automatiquement confirmée ?','Non. Elle dépend de la disponibilité des professionnels, de l’adéquation au besoin, des conditions de la propriété et de la confirmation finale.')],
'car': [('Que doit contenir une demande de location de voiture de luxe à Ibiza ?','Indiquez les dates, la catégorie de véhicule, les exigences liées au conducteur, les points de livraison et de reprise, les passagers et les besoins en bagages.'),('La voiture peut-elle être coordonnée avec la villa ou le reste du séjour ?','Oui. Livraison du véhicule, accès à la villa, chauffeur et autres services confirmés peuvent être alignés autour du même séjour.'),('Que se passe-t-il si le modèle demandé n’est pas disponible ?','Des alternatives comparables peuvent être proposées selon les priorités du client. Modèles exacts, spécifications et disponibilité restent soumis à confirmation du fournisseur.'),('Les conditions de location sont-elles identiques pour tous les véhicules ?','Non. Âge, permis, dépôt, assurance, kilométrage et conditions de livraison peuvent varier selon le fournisseur et le véhicule.')],
'wellness': [('Quelles informations sont utiles pour organiser des services wellness à Ibiza ?','Partagez les dates, le lieu, le nombre de personnes, le soin ou la pratique souhaitée, l’horaire et les préférences utiles à la mise en place.'),('Des rendez-vous wellness peuvent-ils être organisés dans une villa ?','Lorsque le praticien et les conditions de la propriété le permettent, des séances en villa peuvent être coordonnées avec le reste du programme.'),('Le programme wellness peut-il évoluer pendant le séjour ?','Oui, sous réserve de disponibilité du praticien. Horaires et services peuvent être réévalués avec l’évolution de l’itinéraire.'),('La coordination wellness remplace-t-elle un avis médical ?','Non. Ibiza VIP Move coordonne des services d’hospitality et de wellness. Les questions médicales, diagnostics ou traitements doivent être confiés à des professionnels de santé qualifiés.')],
'events': [('Que doit contenir un brief pour un événement privé à Ibiza ?','Date, nombre d’invités, lieu ou type d’espace, style d’événement, horaires et besoins connus en transport, personnel, sécurité, restauration ou divertissement.'),('Transport, sécurité et personnel peuvent-ils être coordonnés avec l’événement ?','Oui. Ces éléments peuvent être organisés autour d’un même timing afin que les arrivées, mouvements et équipes travaillent avec le même brief.'),('Peut-on commencer si certains détails ne sont pas encore décidés ?','Oui. La date, le nombre d’invités et l’orientation du lieu suffisent pour commencer pendant que les autres éléments sont précisés.'),('Les lieux, fournisseurs ou autorisations sont-ils garantis ?','Non. L’accès, les fournisseurs, autorisations et exigences particulières restent soumis aux disponibilités, contrats, règles des propriétés et validations applicables.')],
'bespoke': [('Qu’est-ce qu’une demande de conciergerie sur mesure ?','C’est une demande qui ne correspond pas à une seule catégorie et qui peut nécessiter plusieurs fournisseurs, lieux ou étapes opérationnelles coordonnés.'),('Quelles informations sont utiles pour une demande sur mesure ?','Partagez l’objectif, les dates, le profil des invités, les lieux, les horaires, les contraintes et ce qui est déjà confirmé.'),('Plusieurs services peuvent-ils être combinés dans un même brief ?','Oui. C’est particulièrement utile lorsque transport, villa, dining, personnel, sécurité, événements ou autres services doivent fonctionner comme un seul itinéraire.'),('Toutes les demandes sur mesure peuvent-elles être organisées ?','Non. Les demandes doivent être légales, sûres, réalisables et compatibles avec les disponibilités, règles des propriétés et exigences locales. Rien n’est considéré comme confirmé avant vérification.')]
},
'de': {
'chef': [('Welche Informationen helfen bei der Anfrage für Privatkoch oder Villa-Staff auf Ibiza?','Teilen Sie Reisedaten, Gästezahl, Lage der Immobilie, gewünschten Servicestil, Ernährungsanforderungen und bekannten Personalbedarf mit.'),('Können Koch und Personal mit dem restlichen Aufenthalt koordiniert werden?','Ja. Essenszeiten, Villenzugang, Chauffeur-Fahrten, Events und Gästepläne können rund um denselben Ablauf abgestimmt werden.'),('Was passiert, wenn sich Gästezahl oder Zeiten ändern?','Betroffene Services und Einsatzzeiten können anhand der neuen Informationen neu abgestimmt werden. Frühe Mitteilung hilft, da Verfügbarkeit und Vorbereitung variieren können.'),('Ist jede Anfrage für Koch oder Staffing automatisch bestätigt?','Nein. Sie hängt von professioneller Verfügbarkeit, Eignung, Bedingungen der Immobilie und finaler Bestätigung ab.')],
'car': [('Welche Angaben sollte eine Anfrage für Luxusautovermietung auf Ibiza enthalten?','Reisedaten, Fahrzeugkategorie, Fahreranforderungen, Liefer- und Abholorte, Passagierbedarf und Gepäck helfen bei der Planung.'),('Kann das Fahrzeug mit Villa oder Concierge-Ablauf koordiniert werden?','Ja. Fahrzeuglieferung, Villenzugang, Chauffeur-Unterstützung und andere bestätigte Services können um denselben Aufenthalt abgestimmt werden.'),('Was passiert, wenn das gewünschte Modell nicht verfügbar ist?','Vergleichbare Alternativen können entsprechend den Prioritäten besprochen werden. Exakte Modelle, Spezifikationen und Verfügbarkeit bleiben von der Bestätigung des Anbieters abhängig.'),('Sind die Mietbedingungen bei jedem Fahrzeug gleich?','Nein. Alter, Führerschein, Kaution, Versicherung, Kilometer und Lieferbedingungen können je nach Anbieter und Fahrzeug variieren.')],
'wellness': [('Welche Informationen helfen bei der Organisation von Wellness-Services auf Ibiza?','Teilen Sie Daten, Ort, Gästezahl, gewünschte Behandlung oder Praxis, Zeitplan und relevante Präferenzen für die Organisation mit.'),('Können Wellness-Termine in einer Villa koordiniert werden?','Wenn Anbieter und Bedingungen der Immobilie es zulassen, können Termine in der Villa mit dem restlichen Ablauf koordiniert werden.'),('Kann sich der Wellness-Plan während des Aufenthalts ändern?','Ja, vorbehaltlich Verfügbarkeit des Anbieters. Zeiten und Services können mit dem Reiseplan angepasst werden.'),('Ersetzt Wellness-Koordination medizinische Beratung?','Nein. Ibiza VIP Move koordiniert Hospitality- und Wellness-Services. Medizinische Fragen, Diagnosen oder Behandlungen gehören in die Hände qualifizierter medizinischer Fachkräfte.')],
'events': [('Welche Angaben sollte ein Briefing für ein privates Event auf Ibiza enthalten?','Datum, Gästezahl, Location oder gewünschtes Setting, Eventstil, Timing und bekannte Anforderungen an Transport, Personal, Security, Catering oder Entertainment.'),('Können Transport, Security und Personal mit dem Event koordiniert werden?','Ja. Diese Elemente können um einen gemeinsamen Ablauf geplant werden, damit Ankünfte, Gästebewegungen und Teams mit demselben Briefing arbeiten.'),('Kann die Planung beginnen, wenn noch nicht alle Details feststehen?','Ja. Datum, Gästezahl und grundsätzliche Location-Richtung reichen für den Start, während weitere Elemente präzisiert werden.'),('Sind Locations, Anbieter oder Genehmigungen garantiert?','Nein. Zugang, Anbieter, Genehmigungen und spezielle Anforderungen hängen von Verfügbarkeit, Verträgen, Property-Regeln und anwendbaren Freigaben ab.')],
'bespoke': [('Was ist eine maßgeschneiderte Concierge-Anfrage?','Eine Anfrage, die nicht in eine einzelne Servicekategorie passt und mehrere Anbieter, Orte oder operative Schritte miteinander verbinden kann.'),('Welche Informationen sind für eine Bespoke-Anfrage hilfreich?','Teilen Sie Ziel, Daten, Gästeprofil, Orte, Zeiten, Einschränkungen und bereits bestätigte Elemente mit.'),('Können mehrere Services in einem Briefing kombiniert werden?','Ja. Das ist besonders sinnvoll, wenn Transport, Villa, Dining, Personal, Security, Events oder andere Services als ein Ablauf funktionieren sollen.'),('Kann jede maßgeschneiderte Anfrage organisiert werden?','Nein. Anfragen müssen legal, sicher, realisierbar und mit Verfügbarkeit, Property-Regeln und lokalen Anforderungen vereinbar sein. Nichts gilt vor Prüfung als bestätigt.')]
},
'ar': {
'chef': [('ما المعلومات المفيدة عند طلب طاهٍ خاص أو طاقم للفيلا في إيبيزا؟','شارك التواريخ وعدد الضيوف وموقع العقار ونمط الخدمة المطلوب والمتطلبات الغذائية وأي احتياجات معروفة للطاقم.'),('هل يمكن تنسيق الطاهي والطاقم مع بقية الإقامة؟','نعم. يمكن تنسيق مواعيد الوجبات ودخول الفيلا والتنقلات والفعاليات وجدول الضيوف ضمن خطة واحدة.'),('ماذا يحدث إذا تغيّر عدد الضيوف أو التوقيت؟','يمكن مراجعة الخدمات والفترات المتأثرة وفق المعلومات الجديدة. الإبلاغ المبكر مفيد لأن التوافر ومتطلبات التجهيز قد تتغير.'),('هل يتم تأكيد كل طلب للطاهي أو الطاقم تلقائياً؟','لا. يعتمد ذلك على توافر المهنيين وملاءمتهم للخدمة وظروف العقار والتأكيد النهائي.')],
'car': [('ما المعلومات المطلوبة لطلب سيارة فاخرة للإيجار في إيبيزا؟','شارك التواريخ وفئة السيارة ومتطلبات السائق ونقاط التسليم والاستلام وعدد الركاب واحتياجات الأمتعة.'),('هل يمكن تنسيق السيارة مع الفيلا أو بقية خدمات الكونسيرج؟','نعم. يمكن تنسيق تسليم السيارة ودخول الفيلا ودعم السائق والخدمات المؤكدة الأخرى ضمن الإقامة نفسها.'),('ماذا يحدث إذا لم يكن الموديل المطلوب متاحاً؟','يمكن مناقشة بدائل مشابهة حسب أولويات العميل. الموديلات والمواصفات الدقيقة والتوافر تخضع دائماً لتأكيد المورّد.'),('هل شروط الإيجار متطابقة لكل السيارات؟','لا. قد تختلف متطلبات العمر والرخصة والتأمين والتأمين المالي والمسافة وشروط التسليم حسب المورّد والسيارة.')],
'wellness': [('ما المعلومات المفيدة لتنظيم خدمات العافية في إيبيزا؟','شارك التواريخ والموقع وعدد الضيوف ونوع الجلسة أو الممارسة المفضلة والتوقيت وأي تفضيلات تساعد في التجهيز.'),('هل يمكن تنظيم جلسات العافية داخل الفيلا؟','عندما يسمح مقدم الخدمة وظروف العقار بذلك، يمكن تنسيق الجلسات داخل الفيلا مع بقية البرنامج.'),('هل يمكن تعديل خطة العافية أثناء الإقامة؟','نعم، بحسب توافر مقدم الخدمة. يمكن مراجعة المواعيد والخدمات مع تطور البرنامج.'),('هل تنسيق خدمات العافية يغني عن الاستشارة الطبية؟','لا. تقوم Ibiza VIP Move بتنسيق خدمات الضيافة والعافية فقط. الأسئلة الطبية أو التشخيص أو العلاج يجب أن يتولاها مختصون صحيون مؤهلون.')],
'events': [('ما الذي يجب أن يتضمنه ملخص فعالية خاصة في إيبيزا؟','التاريخ وعدد الضيوف والموقع أو نوع المكان وأسلوب الفعالية والتوقيت والاحتياجات المعروفة للنقل والطاقم والأمن والطعام أو الترفيه.'),('هل يمكن تنسيق النقل والأمن والطاقم مع الفعالية؟','نعم. يمكن تنظيم هذه العناصر حول جدول واحد حتى تعمل الوصولات وتنقلات الضيوف والفرق وفق نفس الخطة.'),('هل يمكن بدء التخطيط قبل حسم كل التفاصيل؟','نعم. يكفي التاريخ وعدد الضيوف والاتجاه العام للمكان للبدء، ثم يمكن استكمال العناصر الأخرى لاحقاً.'),('هل الأماكن والموردون والتصاريح مضمونة؟','لا. تخضع الأماكن والموردون والتصاريح والمتطلبات الخاصة للتوافر والعقود وقواعد العقار والموافقات القانونية أو التشغيلية المطبقة.')],
'bespoke': [('ما هو طلب الكونسيرج المصمم حسب الطلب؟','هو طلب لا يندرج ضمن خدمة واحدة وقد يحتاج إلى تنسيق عدة موردين أو مواقع أو خطوات تشغيلية معاً.'),('ما المعلومات المفيدة لطلب مخصص؟','شارك الهدف والتواريخ وطبيعة الضيوف والمواقع والتوقيت والقيود وما تم تأكيده مسبقاً.'),('هل يمكن جمع عدة خدمات في طلب واحد؟','نعم. يكون ذلك مفيداً عندما تحتاج خدمات النقل والفيلا والمطاعم والطاقم والأمن والفعاليات أو غيرها إلى العمل ضمن برنامج واحد.'),('هل يمكن تنفيذ كل طلب مخصص؟','لا. يجب أن يكون الطلب قانونياً وآمناً وقابلاً للتنفيذ ومتوافقاً مع التوافر وقواعد العقارات والمتطلبات المحلية. لا يعتبر أي عنصر مؤكداً قبل التحقق منه.')]
}
}

PATHS = {
'en': {'chef':'/private-chef-staffing-ibiza/','car':'/luxury-car-rental-ibiza/','wellness':'/wellness-ibiza/','events':'/private-events-ibiza/','bespoke':'/bespoke-concierge-ibiza/'},
'es': {'chef':'/es/chef-privado-staffing-ibiza/','car':'/es/alquiler-coches-lujo-ibiza/','wellness':'/es/wellness-ibiza/','events':'/es/eventos-privados-ibiza/','bespoke':'/es/concierge-a-medida-ibiza/'},
'fr': {'chef':'/fr/chef-prive-personnel-villa-ibiza/','car':'/fr/location-voiture-luxe-ibiza/','wellness':'/fr/wellness-ibiza/','events':'/fr/evenements-prives-ibiza/','bespoke':'/fr/conciergerie-sur-mesure-ibiza/'},
'de': {'chef':'/de/privatkoch-villa-staff-ibiza/','car':'/de/luxusauto-mieten-ibiza/','wellness':'/de/wellness-ibiza/','events':'/de/private-events-ibiza/','bespoke':'/de/bespoke-concierge-ibiza/'},
'ar': {'chef':'/ar/private-chef-staffing-ibiza/','car':'/ar/luxury-car-rental-ibiza/','wellness':'/ar/wellness-ibiza/','events':'/ar/private-events-ibiza/','bespoke':'/ar/bespoke-concierge-ibiza/'}
}

HEAD = {
'en': ('Before the private brief','What clients usually need to know.','Short operational answers to the questions that most often shape the first conversation.','Service planning questions'),
'es': ('Antes del brief privado','Lo que los clientes suelen necesitar saber.','Respuestas operativas breves a las preguntas que suelen definir la primera conversación.','Preguntas de planificación del servicio'),
'fr': ('Avant le brief privé','Ce que les clients souhaitent généralement savoir.','Des réponses opérationnelles courtes aux questions qui structurent le premier échange.','Questions de planification du service'),
'de': ('Vor dem privaten Briefing','Was Kunden normalerweise wissen möchten.','Kurze operative Antworten auf Fragen, die das erste Gespräch häufig bestimmen.','Fragen zur Serviceplanung'),
'ar': ('قبل الملخص الخاص','ما يحتاج العملاء عادة إلى معرفته.','إجابات تشغيلية مختصرة على الأسئلة التي تحدد المحادثة الأولى غالباً.','أسئلة تخطيط الخدمة')
}

def schema(items):
    return {'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in items]}

def remove_faq_schema(html):
    pattern=re.compile(r'<script\s+type="application/ld\+json">(.*?)</script>',re.I|re.S)
    out=[]; pos=0
    for m in pattern.finditer(html):
        out.append(html[pos:m.start()])
        keep=True
        try:
            obj=json.loads(m.group(1))
            if isinstance(obj,dict) and obj.get('@type')=='FAQPage': keep=False
        except Exception: pass
        if keep: out.append(m.group(0))
        pos=m.end()
    out.append(html[pos:])
    return ''.join(out)

count=0
for lang, services in PATHS.items():
    eyebrow,title,intro,aria=HEAD[lang]
    for key,path in services.items():
        items=COPY[lang][key]
        p=ROOT/path.strip('/')/'index.html'
        if not p.exists(): raise SystemExit(f'Phase 74 missing page: {path}')
        html=p.read_text(encoding='utf-8')
        # Replace any previous FAQ block if present so the page has exactly one visible FAQ section.
        html=re.sub(r'<section class="ivm-service-faq".*?</section>','',html,flags=re.I|re.S)
        details=''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)
        section=(f'<section class="ivm-service-faq" aria-label="{aria}"><div class="ivm-service-faq-inner">'
                 f'<div class="ivm-service-faq-head"><div class="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{intro}</p></div>'
                 f'<div class="ivm-faq-list">{details}</div></div></section>')
        html=html.replace('</main>',section+'</main>',1)
        html=remove_faq_schema(html)
        data=json.dumps(schema(items),ensure_ascii=False,separators=(',',':'))
        html=html.replace('</head>',f'<script type="application/ld+json">{data}</script></head>',1)
        p.write_text(html,encoding='utf-8')
        count+=1

if count != 25: raise SystemExit(f'Phase 74 expected 25 pages, got {count}')
for lang, services in PATHS.items():
    for key,path in services.items():
        html=(ROOT/path.strip('/')/'index.html').read_text(encoding='utf-8')
        if html.count('class="ivm-service-faq"') != 1: raise SystemExit(f'Phase 74 FAQ section count: {path}')
        sec=re.search(r'<section class="ivm-service-faq".*?</section>',html,re.I|re.S)
        if not sec or sec.group(0).count('<details>') != 4: raise SystemExit(f'Phase 74 FAQ item count: {path}')
        schemas=[]
        for m in re.finditer(r'<script\s+type="application/ld\+json">(.*?)</script>',html,re.I|re.S):
            try: obj=json.loads(m.group(1))
            except Exception: continue
            if isinstance(obj,dict) and obj.get('@type')=='FAQPage': schemas.append(obj)
        if len(schemas)!=1 or len(schemas[0].get('mainEntity',[]))!=4: raise SystemExit(f'Phase 74 FAQ schema: {path}')
        if html.count('<h1')!=1: raise SystemExit(f'Phase 74 H1 count: {path}')
        if STYLE not in html: raise SystemExit(f'Phase 74 base FAQ CSS missing: {path}')

print('PASS: Phase 74 lifestyle decision FAQs — 25 landings, 100 localized questions, one visible FAQ + FAQPage schema per page')
