"""Integrate the user-supplied Ibiza VIP Move vocabulary into existing B2B pages.

Phase 140 intentionally creates no new URLs. It adds professional-role language only where
it explains who can brief Ibiza VIP Move or who can receive local Ibiza support.
"""
from pathlib import Path

ROOT = Path('_site')
MARKER = '<section class="ivm-b2b-overview ivm-phase140-vocabulary"'
CTA = '<section class="ivm-b2b-cta">'

COPY = {
    'partners': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-en-partners"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Professional client roles</div><h2 id="ivm140-en-partners">Professional profiles we can support in Ibiza.</h2></div><div><p>An active Ibiza brief can come from a Luxury travel advisor, Travel designer, Destination specialist, Independent travel agent, Boutique travel agency, Luxury tour operator or Destination management company (DMC). We provide the local Ibiza execution described above; these labels do not represent separate Ibiza VIP Move services.</p><p>We can also coordinate confirmed local services for a Lifestyle Coordinator, VIP Host, Artist Liaison or Tour Manager when their client, guest or artist needs Ibiza transport, accommodation coordination and other services within our existing scope.</p></div></div></section>''',
    'private-office': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-en-office"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Private team roles</div><h2 id="ivm140-en-office">Private household and residence teams.</h2></div><div><p>For an active Ibiza stay, we can coordinate within our existing scope for a Private personal assistant, Executive assistant or Guest relations manager, as well as a Family Assistant, Household Manager, Estate Manager or Director of Residences acting for a principal or family.</p><p>This means local Ibiza coordination only: it does not mean Ibiza VIP Move manages the household, estate or residence itself.</p></div></div></section>''',
    'fr/partners': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-fr-partners"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Profils clients professionnels</div><h2 id="ivm140-fr-partners">Les professionnels que nous pouvons accompagner à Ibiza.</h2></div><div><p>Un brief actif à Ibiza peut venir d’un Conseiller en voyages de luxe, d’un Créateur de voyages, d’un Spécialiste de la destination, d’un Agent de voyages indépendant, d’une Agence de voyages à taille humaine, d’un Tour-opérateur de luxe ou d’une Agence réceptive (DMC). Ces appellations décrivent les professionnels que nous pouvons soutenir et non de nouveaux services Ibiza VIP Move.</p><p>Nous pouvons aussi coordonner des services locaux confirmés pour un Coordinateur de voyages et de services lifestyle, un Hôte VIP, un Chargé de l’accueil des artistes ou un Responsable de tournée lorsque leur client, invité ou artiste a besoin de transport, de coordination d’hébergement ou d’autres services déjà proposés à Ibiza.</p></div></div></section>''',
    'fr/private-office': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-fr-office"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Rôles des équipes privées</div><h2 id="ivm140-fr-office">Équipes de maisons et résidences privées.</h2></div><div><p>Pour un séjour actif à Ibiza, nous pouvons coordonner dans notre périmètre pour un Assistant personnel privé, un Assistant de direction ou un Responsable des relations clients, ainsi que pour un Assistant personnel de famille, un Intendant de maison, un Intendant de propriétés privées ou un Directeur de résidences privées agissant pour un principal ou une famille.</p><p>Il s’agit uniquement de coordination locale à Ibiza : Ibiza VIP Move ne se présente pas comme gestionnaire de la maison, de la propriété ou de la résidence.</p></div></div></section>''',
    'de/partners': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-de-partners"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Professionelle Kundenrollen</div><h2 id="ivm140-de-partners">Professionelle Profile, die wir auf Ibiza unterstützen können.</h2></div><div><p>Ein aktives Ibiza-Briefing kann von einem Luxusreiseberater, Reisedesigner, Destinationsspezialist oder Selbstständiger Reiseberater sowie von einem Boutique-Reisebüro, Luxusreiseveranstalter oder einer Destinationsmanagement-Agentur (DMC) kommen. Diese Bezeichnungen beschreiben mögliche professionelle Auftraggeber oder Partner und keine neuen Ibiza VIP Move Services.</p><p>Wir können außerdem bestätigte lokale Leistungen für einen Koordinator für Reise- und Lifestyle-Services, VIP-Gästebetreuer, Künstlerbetreuer oder Tourmanager für Musikproduktionen koordinieren, wenn deren Kunde, Gast oder Künstler Transport, Unterkunftskoordination oder andere bestehende Ibiza-Leistungen benötigt.</p></div></div></section>''',
    'de/private-office': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-de-office"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Rollen privater Teams</div><h2 id="ivm140-de-office">Private Haushalts- und Residenzteams.</h2></div><div><p>Für einen aktiven Ibiza-Aufenthalt können wir innerhalb unseres bestehenden Umfangs für einen Privatassistent, eine Assistenz der Geschäftsführung oder einen Guest Relations Manager sowie für eine Private Familienassistenz, einen Hausmanager für Privathaushalte, einen Verwalter privater Anwesen oder einen Leiter privater Residenzen koordinieren, wenn sie für einen Principal oder eine Familie handeln.</p><p>Gemeint ist ausschließlich lokale Koordination auf Ibiza: Ibiza VIP Move übernimmt damit nicht die Verwaltung des Haushalts, Anwesens oder der Residenz.</p></div></div></section>''',
    'ar/partners': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-ar-partners"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">أدوار مهنية للعملاء</div><h2 id="ivm140-ar-partners">الملفات المهنية التي يمكننا دعمها في إيبيزا.</h2></div><div><p>يمكن أن يأتي طلب فعلي في إيبيزا من مستشار سفر فاخر أو مصمم رحلات أو خبير وجهات سياحية أو وكيل سفر مستقل أو وكالة سفر متخصصة أو منظم رحلات فاخرة أو شركة إدارة الوجهات السياحية (DMC). تصف هذه المسميات المهنيين الذين يمكننا دعمهم، ولا تمثل خدمات جديدة لدى Ibiza VIP Move.</p><p>كما يمكننا تنسيق الخدمات المحلية المؤكدة لصالح منسق خدمات السفر ونمط الحياة أو مضيف كبار الشخصيات أو منسق شؤون الفنانين أو مدير الجولات الفنية عندما يحتاج عميلهم أو ضيفهم أو الفنان إلى النقل في إيبيزا أو تنسيق الإقامة أو خدمات أخرى ضمن نطاقنا الحالي.</p></div></div></section>''',
    'ar/private-office': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-ar-office"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">أدوار الفرق الخاصة</div><h2 id="ivm140-ar-office">فرق المنازل والمساكن الخاصة.</h2></div><div><p>خلال إقامة فعلية في إيبيزا، يمكننا التنسيق ضمن نطاقنا الحالي لصالح مساعد شخصي خاص أو مساعد تنفيذي أو مدير علاقات الضيوف، وكذلك لصالح مساعد شخصي للعائلة أو مدير شؤون المنزل أو مدير الأملاك السكنية الخاصة أو مدير المساكن الخاصة عندما يعملون لصالح ضيف رئيسي أو عائلة.</p><p>المقصود هو التنسيق المحلي في إيبيزا فقط؛ ولا يعني ذلك أن Ibiza VIP Move تدير المنزل أو الأملاك أو المسكن نفسه.</p></div></div></section>''',
    'es/partners': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-es-partners"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Perfiles profesionales</div><h2 id="ivm140-es-partners">Profesionales a los que podemos apoyar en Ibiza.</h2></div><div><p>Un brief activo en Ibiza puede llegar de un Asesor de viajes de lujo, Diseñador de viajes, Especialista en destinos, Agente de viajes independiente, Agencia boutique de viajes, Operador de viajes de lujo o Agencia receptiva (DMC). Estas denominaciones describen profesionales a los que podemos apoyar y no nuevos servicios de Ibiza VIP Move.</p><p>También podemos coordinar servicios locales confirmados para un Coordinador de viajes y servicios lifestyle, Anfitrión VIP, Coordinador de atención a artistas o Mánager de giras musicales cuando su cliente, huésped o artista necesite transporte, coordinación de alojamiento u otros servicios ya existentes en Ibiza.</p></div></div></section>''',
    'es/private-office': '''<section class="ivm-b2b-overview ivm-phase140-vocabulary" aria-labelledby="ivm140-es-office"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">Roles de equipos privados</div><h2 id="ivm140-es-office">Equipos de hogares y residencias privadas.</h2></div><div><p>Para una estancia activa en Ibiza, podemos coordinar dentro de nuestro alcance para un Asistente personal privado, Asistente ejecutivo o Responsable de relaciones con huéspedes, así como para un Asistente personal de familias, Administrador del hogar, Gestor de propiedades residenciales privadas o Director de residencias privadas que actúe para un principal o una familia.</p><p>Esto significa únicamente coordinación local en Ibiza: Ibiza VIP Move no se presenta como gestor del hogar, la propiedad o la residencia.</p></div></div></section>''',
}

def enhance():
    changed = 0
    for slug, block in COPY.items():
        path = ROOT / slug / 'index.html'
        html = path.read_text(encoding='utf-8')
        if MARKER in html:
            if html.count(MARKER) != 1:
                raise SystemExit(f'Phase 140: duplicate vocabulary block in {slug}')
            continue
        if html.count(CTA) != 1:
            raise SystemExit(f'Phase 140: expected one B2B CTA in {slug}')
        html = html.replace(CTA, block + CTA, 1)
        path.write_text(html, encoding='utf-8')
        changed += 1
    print(f'PASS: Phase 140 — vocabulary integrated into {changed} existing B2B pages; no new URL created')

if __name__ == '__main__':
    enhance()
