from pathlib import Path
from html import escape
import json,re

ROOT=Path('_site'); BASE='https://ibizavipmove.com'; ORG=BASE+'/#organization'; EMAIL='partnership@ibizavipmove.com'; WA='https://wa.me/34600703303'
SHELL={'es':'es/sobre-nosotros/index.html','fr':'fr/a-propos/index.html','de':'de/ueber-uns/index.html','ar':'ar/about/index.html'}
CONTACT={'es':'/es/contacto/','fr':'/fr/contact/','de':'/de/kontakt/','ar':'/ar/contact/'}
SERVICES={
'es':[('/es/concierge-privado-ibiza/','Concierge privado'),('/es/chauffeur-privado-ibiza/','Chauffeur privado'),('/es/villas-lujo-ibiza/','Villas de lujo'),('/es/yate-privado-ibiza/','Yates & charters'),('/es/restaurantes-nightlife-ibiza/','Dining & Nightlife'),('/es/aviacion-privada-ibiza/','Aviación privada'),('/es/seguridad-privada-ibiza/','Seguridad privada'),('/es/chef-privado-staffing-ibiza/','Chef & villa staffing'),('/es/alquiler-coches-lujo-ibiza/','Luxury car rental'),('/es/wellness-ibiza/','Wellness & beauty'),('/es/eventos-privados-ibiza/','Eventos privados')],
'fr':[('/fr/conciergerie-privee-ibiza/','Conciergerie privée'),('/fr/chauffeur-prive-ibiza/','Chauffeur privé'),('/fr/villas-luxe-ibiza/','Villas de luxe'),('/fr/location-yacht-ibiza/','Yachts & charters'),('/fr/restaurants-nightlife-ibiza/','Dining & Nightlife'),('/fr/aviation-privee-ibiza/','Aviation privée'),('/fr/securite-privee-ibiza/','Sécurité privée'),('/fr/chef-prive-personnel-villa-ibiza/','Chef & personnel villa'),('/fr/location-voiture-luxe-ibiza/','Location voiture de luxe'),('/fr/wellness-ibiza/','Wellness & beauty'),('/fr/evenements-prives-ibiza/','Événements privés')],
'de':[('/de/privater-concierge-ibiza/','Privater Concierge'),('/de/privater-chauffeur-ibiza/','Privater Chauffeur'),('/de/luxusvillen-ibiza/','Luxusvillen'),('/de/yachtcharter-ibiza/','Yachten & Charters'),('/de/restaurants-nightlife-ibiza/','Dining & Nightlife'),('/de/private-aviation-ibiza/','Private Aviation'),('/de/private-sicherheit-ibiza/','Private Sicherheit'),('/de/privatkoch-villa-staff-ibiza/','Privatkoch & Villa Staff'),('/de/luxusauto-mieten-ibiza/','Luxusauto mieten'),('/de/wellness-ibiza/','Wellness & Beauty'),('/de/private-events-ibiza/','Private Events')],
'ar':[('/ar/private-concierge-ibiza/','الكونسيرج الخاص'),('/ar/private-chauffeur-ibiza/','السائق الخاص'),('/ar/luxury-villas-ibiza/','الفلل الفاخرة'),('/ar/yacht-charter-ibiza/','اليخوت والرحلات البحرية'),('/ar/restaurants-nightlife-ibiza/','المطاعم والحياة الليلية'),('/ar/private-aviation-ibiza/','الطيران الخاص'),('/ar/private-security-ibiza/','الأمن الخاص'),('/ar/private-chef-staffing-ibiza/','الشيف وطاقم الفيلا'),('/ar/luxury-car-rental-ibiza/','تأجير السيارات الفاخرة'),('/ar/wellness-ibiza/','العافية والجمال'),('/ar/private-events-ibiza/','الفعاليات الخاصة')]}
COPY={
'es':dict(title='Información oficial para medios y partners | Ibiza VIP Move',desc='Información oficial de Ibiza VIP Move para periodistas, directorios, travel advisors, concierge companies y partners comerciales.',kicker='Media · Trade · Partners',h1='Información oficial para medios y partners.',intro='Una única fuente de información factual sobre Ibiza VIP Move para periodistas, directorios, profesionales del viaje, empresas de concierge y partners comerciales.',truth='Una sola fuente de verdad.',truthp='Ibiza VIP Move es un servicio de concierge privado y coordinación de lifestyle de lujo centrado en las necesidades de clientes en Ibiza, España.',quote='Fácil de citar. Fácil de verificar.',quotep='Coordinamos chauffeur privado, villas, yates, aviación, dining y nightlife, seguridad, staffing, wellness, eventos y solicitudes bespoke a través de un punto de contacto local.',brand='Archivos de marca y referencias.',brandp='Los archivos se facilitan para referencia factual o editorial. No alteres el nombre ni atribuyas endorsements o servicios no confirmados por la compañía.',links='Enlaza al servicio específico.',linksp='Para referencias generales usa la homepage. Para una referencia editorial o de partner sobre un servicio concreto, usa la URL oficial correspondiente.',facts='Factual por diseño.',factslist=['Usa únicamente información confirmada directamente por la compañía.','Reservas, inventario, acceso y disponibilidad de proveedores están sujetos a confirmación.','No impliques endorsement de celebrities, hoteles, venues o partners sin autorización explícita.','Usa el sitio oficial y los datos de contacto indicados para verificar la marca.'],cta='¿Consulta de medios o partnership?',ctap='Para verificación factual, solicitudes editoriales o introducciones comerciales, contacta con el partnerships desk.',btn='Email Partnerships'),
'fr':dict(title='Informations officielles médias & partenaires | Ibiza VIP Move',desc='Informations officielles Ibiza VIP Move pour journalistes, annuaires, travel advisors, sociétés de conciergerie et partenaires commerciaux.',kicker='Media · Trade · Partners',h1='Informations officielles pour médias et partenaires.',intro='Une source unique d’informations factuelles sur Ibiza VIP Move pour journalistes, annuaires, professionnels du voyage, sociétés de conciergerie et partenaires.',truth='Une seule source de vérité.',truthp='Ibiza VIP Move est un service de conciergerie privée et de coordination lifestyle de luxe centré sur les besoins des clients à Ibiza, Espagne.',quote='Facile à citer. Facile à vérifier.',quotep='Nous coordonnons chauffeur privé, villas, yachts, aviation, dining et nightlife, sécurité, staffing, wellness, événements et demandes sur mesure via un point de contact local.',brand='Fichiers de marque et références.',brandp='Ces fichiers sont fournis pour référence factuelle ou éditoriale. Ne modifiez pas le nom et n’attribuez aucun endorsement ou service non confirmé par la société.',links='Lien vers le service précis.',linksp='Pour une référence générale, utilisez la homepage. Pour un service précis, utilisez son URL officielle ci-dessous.',facts='Factual par conception.',factslist=['Utilisez uniquement les informations confirmées directement par la société.','Réservations, inventaire, accès et disponibilité fournisseurs restent soumis à confirmation.','N’impliquez aucun endorsement de célébrité, hôtel, venue ou partenaire sans autorisation explicite.','Utilisez le site officiel et les coordonnées indiquées pour vérifier la marque.'],cta='Demande média ou partenariat ?',ctap='Pour vérification factuelle, demande éditoriale ou introduction commerciale, contactez le partnerships desk.',btn='Email Partnerships'),
'de':dict(title='Offizielle Medien- & Partnerinformationen | Ibiza VIP Move',desc='Offizielle Informationen von Ibiza VIP Move für Journalisten, Verzeichnisse, Travel Advisors, Concierge-Unternehmen und Geschäftspartner.',kicker='Media · Trade · Partners',h1='Offizielle Informationen für Medien und Partner.',intro='Eine zentrale Quelle mit verifizierbaren Informationen über Ibiza VIP Move für Journalisten, Verzeichnisse, Travel Professionals, Concierge-Unternehmen und Partner.',truth='Eine verlässliche Informationsquelle.',truthp='Ibiza VIP Move ist ein privater Concierge- und Luxury-Lifestyle-Koordinationsservice für Kundenanforderungen auf Ibiza, Spanien.',quote='Einfach zu zitieren. Einfach zu prüfen.',quotep='Wir koordinieren private Chauffeure, Villen, Yachten, Aviation, Dining und Nightlife, Sicherheit, Staffing, Wellness, Events und individuelle Anfragen über einen lokalen Ansprechpartner.',brand='Markendateien und Referenzen.',brandp='Diese Dateien dienen der sachlichen oder redaktionellen Referenz. Namen nicht verändern und keine nicht bestätigten Endorsements oder Leistungen zuschreiben.',links='Zum spezifischen Service verlinken.',linksp='Für allgemeine Markenreferenzen die Homepage verwenden; für einen konkreten Service die jeweilige offizielle URL.',facts='Bewusst faktenbasiert.',factslist=['Nur Informationen verwenden, die direkt vom Unternehmen bestätigt wurden.','Reservierungen, Inventar, Zugang und Lieferantenverfügbarkeit bleiben bestätigungspflichtig.','Keine Celebrity-, Hotel-, Venue- oder Partner-Endorsements ohne ausdrückliche Genehmigung suggerieren.','Zur Markenprüfung die offizielle Website und die angegebenen Kontaktdaten verwenden.'],cta='Medien- oder Partneranfrage?',ctap='Für Faktenprüfung, redaktionelle Anfragen oder kommerzielle Vorstellungen kontaktieren Sie den Partnerships Desk.',btn='Partnerships kontaktieren'),
'ar':dict(title='معلومات رسمية للإعلام والشركاء | Ibiza VIP Move',desc='معلومات Ibiza VIP Move الرسمية للصحفيين والأدلة ومستشاري السفر وشركات الكونسيرج والشركاء التجاريين في قطاع السفر الفاخر.',kicker='Media · Trade · Partners',h1='معلومات رسمية للإعلام والشركاء.',intro='مصدر واحد للمعلومات الدقيقة عن Ibiza VIP Move للصحفيين والأدلة ومحترفي السفر وشركات الكونسيرج والشركاء التجاريين.',truth='مصدر واحد للمعلومات الرسمية.',truthp='Ibiza VIP Move هي خدمة كونسيرج خاص وتنسيق أسلوب حياة فاخر تتمحور حول احتياجات العملاء في إيبيزا، إسبانيا.',quote='سهلة الاقتباس. سهلة التحقق.',quotep='ننسق السائق الخاص والفلل واليخوت والطيران والمطاعم والحياة الليلية والأمن والطاقم والعافية والفعاليات والطلبات الخاصة عبر جهة اتصال محلية واحدة.',brand='ملفات العلامة والمراجع.',brandp='هذه الملفات مخصصة للمرجع الواقعي أو التحريري. لا تغيّر الاسم ولا تنسب تأييداً أو خدمات غير مؤكدة من الشركة.',links='اربط بالخدمة المحددة.',linksp='للمراجع العامة استخدم الصفحة الرئيسية، ولخدمة محددة استخدم رابطها الرسمي أدناه.',facts='معلومات دقيقة بطبيعتها.',factslist=['استخدم فقط المعلومات المؤكدة مباشرة من الشركة.','الحجوزات والمخزون والدخول وتوفر الموردين تظل خاضعة للتأكيد.','لا توحِ بتأييد من مشاهير أو فنادق أو أماكن أو شركاء دون تصريح واضح.','استخدم الموقع الرسمي وبيانات الاتصال الموضحة للتحقق من العلامة.'],cta='استفسار إعلامي أو شراكة؟',ctap='للتحقق من المعلومات أو الطلبات التحريرية أو التعارف التجاري، تواصل مع قسم الشراكات.',btn='مراسلة الشراكات')}

def url(lang): return '/media-partners/' if lang=='en' else f'/{lang}/media-partners/'
def fp(path): return ROOT/path.strip('/')/'index.html'
def alts(): return ''.join(f'<link rel="alternate" hreflang="{l}" href="{BASE}{url(l)}">' for l in ('en','es','fr','de','ar'))+f'<link rel="alternate" hreflang="x-default" href="{BASE}/media-partners/">'
def strip_schema(html):
    pat=re.compile(r'<script\s+type="application/ld\+json">(.*?)</script>',re.I|re.S)
    def f(m):
        try:o=json.loads(m.group(1))
        except:return m.group(0)
        return '' if isinstance(o,dict) and o.get('@type') in ('WebPage','BreadcrumbList') else m.group(0)
    return pat.sub(f,html)
def head(html,c,lang):
    canonical=BASE+url(lang); html=re.sub(r'<title>.*?</title>',f'<title>{escape(c["title"])}</title>',html,count=1,flags=re.I|re.S)
    html=re.sub(r'(<meta\s+name="description"\s+content=")[^"]*(")',lambda m:m.group(1)+escape(c['desc'],quote=True)+m.group(2),html,count=1,flags=re.I)
    html=re.sub(r'<link\b[^>]*rel="canonical"[^>]*>',f'<link rel="canonical" href="{canonical}">',html,count=1,flags=re.I)
    html=re.sub(r'<link\b[^>]*rel="alternate"[^>]*hreflang="[^"]+"[^>]*>','',html,flags=re.I)
    return html.replace('</head>',alts()+'</head>',1)
def main(lang,c):
    links=''.join(f'<a class="ivm-media-service" href="{href}">{escape(label)}</a>' for href,label in SERVICES[lang])
    facts=''.join(f'<li>{escape(x)}</li>' for x in c['factslist'])
    return f'''<main id="main-content"><section class="page-hero"><div class="page-hero-media"><img src="/assets/images/private-office.jpg" alt="Ibiza VIP Move — Media & Partners" width="1800" height="1200" fetchpriority="high" decoding="async"></div><div><div class="kicker light">{escape(c['kicker'])}</div><h1>{escape(c['h1'])}</h1><p>{escape(c['intro'])}</p></div></section><section class="editorial"><div><div class="kicker dark">Official information</div><h2>{escape(c['truth'])}</h2></div><div><p class="large">{escape(c['truthp'])}</p><h2>{escape(c['quote'])}</h2><p>{escape(c['quotep'])}</p></div></section><section class="editorial"><div><div class="kicker dark">Brand assets</div><h2>{escape(c['brand'])}</h2></div><div><p>{escape(c['brandp'])}</p><p><a href="/assets/brand-logo.svg">Primary logo · SVG</a> · <a href="/assets/brand-logo.jpg">Primary logo · JPG</a> · <a href="/assets/brand-mark.svg">Brand mark · SVG</a></p></div></section><section class="ivm-media-links"><div class="ivm-media-links-inner"><h2>{escape(c['links'])}</h2><p>{escape(c['linksp'])}</p><div class="ivm-media-service-grid">{links}</div></div></section><section class="editorial"><div><div class="kicker dark">Verification</div><h2>{escape(c['facts'])}</h2></div><div><ul>{facts}</ul></div></section><section class="closing"><h2>{escape(c['cta'])}</h2><p>{escape(c['ctap'])}</p><div class="hero-actions"><a class="btn dark" href="mailto:{EMAIL}">{escape(c['btn'])}</a><a class="btn ghost" href="{WA}">WhatsApp</a></div></section></main>'''

created=[]
for lang in ('es','fr','de','ar'):
    c=COPY[lang]; shell=(ROOT/SHELL[lang]).read_text(encoding='utf-8'); html=head(strip_schema(shell),c,lang)
    html=re.sub(r'<main\b[^>]*>.*?</main>',main(lang,c),html,count=1,flags=re.I|re.S)
    canonical=BASE+url(lang)
    web={'@context':'https://schema.org','@type':'WebPage','name':c['h1'],'url':canonical,'description':c['desc'],'inLanguage':lang,'about':{'@id':ORG},'publisher':{'@id':ORG}}
    bread={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Ibiza VIP Move','item':BASE+'/'+lang+'/'},{'@type':'ListItem','position':2,'name':c['h1'],'item':canonical}]}
    html=html.replace('</head>','<script type="application/ld+json">'+json.dumps(web,ensure_ascii=False)+'</script><script type="application/ld+json">'+json.dumps(bread,ensure_ascii=False)+'</script></head>',1)
    dst=fp(url(lang)); dst.parent.mkdir(parents=True,exist_ok=True); dst.write_text(html,encoding='utf-8'); created.append(dst)

p=fp('/media-partners/'); t=p.read_text(encoding='utf-8'); t=re.sub(r'<link\b[^>]*rel="alternate"[^>]*hreflang="[^"]+"[^>]*>','',t,flags=re.I); p.write_text(t.replace('</head>',alts()+'</head>',1),encoding='utf-8')
for lang in ('es','fr','de','ar'):
    for p in (ROOT/lang).rglob('*.html'):
        t=p.read_text(encoding='utf-8')
        if 'href="/media-partners/"' in t: p.write_text(t.replace('href="/media-partners/"',f'href="/{lang}/media-partners/"'),encoding='utf-8')
for lang in ('en','es','fr','de','ar'):
    p=fp(url(lang)); t=p.read_text(encoding='utf-8'); assert p.exists() and t.lower().count('<h1')==1; assert t.count('hreflang=')>=6
print(f'PASS: Phase 72 Media & Partners — {len(created)} localized pages + complete five-language cluster')