from pathlib import Path
from html import escape
import json
import re

ROOT=Path('_site')
BASE='https://ibizavipmove.com'
WA='https://wa.me/34600703303'
EMAIL='partnership@ibizavipmove.com'
STYLE='/assets/phase33.css?v=33'
SCRIPT_RE=re.compile(r'<script\s+type="application/ld\+json">(.*?)</script>',re.I|re.S)

PATHS={
'office':{'en':'/private-office/','es':'/es/private-office/','fr':'/fr/private-office/','de':'/de/private-office/','ar':'/ar/private-office/'},
'partners':{'en':'/partners/','es':'/es/partners/','fr':'/fr/partners/','de':'/de/partners/','ar':'/ar/partners/'}
}

DATA={
'es':{
'office':{'title':'Private Office Ibiza | Soporte para PAs y Family Offices | Ibiza VIP Move','desc':'Private Office en Ibiza para principals, familias, personal assistants y family offices que necesitan coordinación local discreta durante estancias complejas.','kicker':'Private Office · Ibiza','h1':'Tu private office en la isla.','lead':'Para principals, familias, personal assistants y family offices que necesitan un único punto de contacto discreto en Ibiza detrás de una estancia compleja.','rail':[('Principals','Gestión privada','Coordinación de alto nivel alrededor del principal y el itinerario confirmado.'),('PAs & EAs','Una línea operativa','Un único contacto local para agendas cambiantes y múltiples servicios.'),('Family Offices','Información need-to-know','Solicitudes privadas con alcance claro y comunicación discreta.'),('Estancias complejas','De llegada a salida','Transporte, villas, acceso, aviación, seguridad y lifestyle alineados.')],'overview_kicker':'Infraestructura para clientes privados','overview_h2':'Menos proveedores que gestionar. Más control.','overview_lead':'El valor no es otra reserva. Es tener un operador local responsable conectando las piezas de la estancia.','overview_p':'Ibiza VIP Move apoya a principals y sus representantes con coordinación práctica en la isla. El servicio puede comenzar antes de la llegada, continuar durante toda la estancia y adaptarse cuando cambia el planning.','audiences':[('Principal y familia','Soporte privado y local de alto nivel'),('Personal assistant','Una línea para ejecutar el itinerario'),('Family office','Coordinación fiable en Ibiza'),('Executive assistant','Comunicación operativa rápida')],'cta_h2':'Pon Ibiza bajo un único punto de contacto.','cta_p':'Envía fechas, perfil de los huéspedes y el nivel de coordinación requerido. Continuamos el brief de forma privada.'},
'partners':{'title':'Partners B2B Ibiza | Operador local para Luxury Travel | Ibiza VIP Move','desc':'Partner local en Ibiza para luxury travel advisors, concierge companies, hospitality, PAs y equipos internacionales que necesitan ejecución privada en la isla.','kicker':'B2B Partnerships · Ibiza','h1':'Tu operador de Ibiza, sobre el terreno.','lead':'Ejecución local para luxury travel advisors, empresas de concierge, hospitality partners, PAs y equipos internacionales de clientes privados.','rail':[('Travel advisors','Ejecución local','Un punto de contacto fiable en Ibiza detrás del itinerario de tu cliente.'),('Concierge firms','Directo o discreto','Soporte de cara al cliente o detrás de escena según el workflow acordado.'),('Hospitality','Logística conectada','Transporte y servicios privados coordinados alrededor del huésped.'),('Equipos internacionales','Comunicación rápida','Coordinación clara por WhatsApp y email antes y durante la estancia.')],'overview_kicker':'Creado para partners profesionales','overview_h2':'Protege la relación con el cliente. Refuerza la ejecución.','overview_lead':'Tu cliente debería vivir un único itinerario fluido, no la complejidad de coordinar proveedores separados en Ibiza.','overview_p':'Apoyamos a partners profesionales con ejecución local en transporte, villas, yates, aviación, dining, nightlife, seguridad, staffing y peticiones a medida. La estructura de comunicación se acuerda según el partner y el brief del cliente.','audiences':[('Luxury travel advisors','Ejecución local para clientes privados'),('Concierge companies','Soporte local entre varios servicios'),('Hotels & hospitality','Logística privada para huéspedes'),('PAs & private offices','Coordinación operativa directa')],'cta_h2':'¿Necesitas un partner de Ibiza al que puedas briefear directamente?','cta_p':'Presenta a tu equipo o envía una solicitud activa de cliente. Aclaramos alcance, disponibilidad y estructura de comunicación preferida.'}},
'fr':{
'office':{'title':'Private Office Ibiza | PAs & Family Offices | Ibiza VIP Move','desc':'Private Office à Ibiza pour principals, familles, personal assistants et family offices ayant besoin d’une coordination locale discrète pendant un séjour complexe.','kicker':'Private Office · Ibiza','h1':'Votre private office sur l’île.','lead':'Pour principals, familles, personal assistants et family offices qui ont besoin d’un seul point de contact discret à Ibiza derrière un séjour complexe.','rail':[('Principals','Gestion privée','Coordination haut de gamme autour du principal et de l’itinéraire confirmé.'),('PAs & EAs','Une ligne opérationnelle','Un seul contact local pour des horaires changeants et plusieurs services.'),('Family Offices','Information need-to-know','Demandes privées gérées avec un périmètre clair et une communication discrète.'),('Séjours complexes','De l’arrivée au départ','Transport, villas, accès, aviation, sécurité et lifestyle alignés.')],'overview_kicker':'Infrastructure client privé','overview_h2':'Moins de fournisseurs à gérer. Plus de contrôle.','overview_lead':'La valeur n’est pas une réservation supplémentaire. C’est un opérateur local responsable qui relie les différentes pièces du séjour.','overview_p':'Ibiza VIP Move accompagne principals et représentants avec une coordination pratique sur l’île. Le service peut commencer avant l’arrivée, se poursuivre pendant le séjour et s’adapter lorsque le programme évolue.','audiences':[('Principal & famille','Support privé local haut de gamme'),('Personal assistant','Une ligne pour exécuter l’itinéraire'),('Family office','Coordination fiable à Ibiza'),('Executive assistant','Communication opérationnelle rapide')],'cta_h2':'Placez Ibiza sous un seul point de contact.','cta_p':'Envoyez les dates, le profil des invités et le niveau de coordination requis. Nous poursuivrons le brief en privé.'},
'partners':{'title':'Partenaires B2B Ibiza | Opérateur local Luxury Travel | Ibiza VIP Move','desc':'Partenaire local à Ibiza pour luxury travel advisors, concierge companies, hospitality, PAs et équipes internationales ayant besoin d’une exécution privée sur l’île.','kicker':'B2B Partnerships · Ibiza','h1':'Votre opérateur Ibiza, sur le terrain.','lead':'Exécution locale pour luxury travel advisors, sociétés de conciergerie, partenaires hospitality, PAs et équipes internationales de clients privés.','rail':[('Travel advisors','Exécution locale','Un point de contact fiable à Ibiza derrière l’itinéraire de votre client.'),('Concierge firms','Direct ou discret','Support client-facing ou en arrière-plan selon le workflow convenu.'),('Hospitality','Logistique connectée','Transport et services privés coordonnés autour des besoins des invités.'),('Équipes internationales','Communication rapide','Coordination claire par WhatsApp et email avant et pendant le séjour.')],'overview_kicker':'Conçu pour les partenaires professionnels','overview_h2':'Protégez la relation client. Renforcez l’exécution.','overview_lead':'Votre client doit vivre un seul itinéraire fluide, pas la complexité de plusieurs fournisseurs à Ibiza.','overview_p':'Nous accompagnons les partenaires professionnels avec une exécution locale sur le transport, les villas, les yachts, l’aviation, le dining, la nightlife, la sécurité, le staffing et les demandes sur mesure. La structure de communication est définie autour du partner et du brief client.','audiences':[('Luxury travel advisors','Exécution sur l’île pour clients privés'),('Concierge companies','Support local multi-services'),('Hotels & hospitality','Logistique privée des invités'),('PAs & private offices','Coordination opérationnelle directe')],'cta_h2':'Besoin d’un partenaire Ibiza à briefer directement ?','cta_p':'Présentez votre équipe ou envoyez une demande client active. Nous clarifierons le périmètre, la disponibilité et le mode de communication souhaité.'}},
'de':{
'office':{'title':'Private Office Ibiza | PAs & Family Offices | Ibiza VIP Move','desc':'Private Office auf Ibiza für Principals, Familien, Personal Assistants und Family Offices, die diskrete lokale Koordination für komplexe Aufenthalte benötigen.','kicker':'Private Office · Ibiza','h1':'Ihr Private Office auf der Insel.','lead':'Für Principals, Familien, Personal Assistants und Family Offices, die hinter einem komplexen Aufenthalt einen diskreten Ibiza-Ansprechpartner benötigen.','rail':[('Principals','Private Betreuung','High-Touch-Koordination rund um Principal und bestätigte Reiseroute.'),('PAs & EAs','Eine operative Linie','Ein lokaler Kontakt für wechselnde Zeitpläne und mehrere Services.'),('Family Offices','Need-to-know Details','Private Anforderungen mit klarem Umfang und diskreter Kommunikation.'),('Komplexe Aufenthalte','Ankunft bis Abreise','Transport, Villen, Access, Aviation, Security und Lifestyle abgestimmt.')],'overview_kicker':'Private Client Infrastructure','overview_h2':'Weniger Supplier Management. Mehr Kontrolle.','overview_lead':'Der Wert ist nicht eine weitere Reservierung. Es ist ein verantwortlicher lokaler Operator, der die beweglichen Teile hinter dem Aufenthalt verbindet.','overview_p':'Ibiza VIP Move unterstützt Principals und ihre Vertreter mit praktischer Koordination auf der Insel. Der Service kann vor der Ankunft beginnen, während des gesamten Aufenthalts weiterlaufen und sich an veränderte Pläne anpassen.','audiences':[('Principal & Familie','Private lokale High-Touch-Unterstützung'),('Personal Assistant','Eine Linie für die Umsetzung der Route'),('Family Office','Zuverlässige Ibiza-Koordination'),('Executive Assistant','Schnelle operative Kommunikation')],'cta_h2':'Ibiza unter einem Ansprechpartner bündeln.','cta_p':'Senden Sie Daten, Gästeprofil und den benötigten Koordinationsumfang. Wir führen das Briefing privat weiter.'},
'partners':{'title':'B2B Partner Ibiza | Local Operator for Luxury Travel | Ibiza VIP Move','desc':'Lokaler Ibiza-Partner für Luxury Travel Advisors, Concierge Companies, Hospitality, PAs und internationale Teams mit Bedarf an privater Ausführung vor Ort.','kicker':'B2B Partnerships · Ibiza','h1':'Ihr Ibiza-Operator vor Ort.','lead':'Lokale Ausführung für Luxury Travel Advisors, Concierge-Unternehmen, Hospitality-Partner, PAs und internationale Private-Client-Teams.','rail':[('Travel Advisors','Lokale Ausführung','Ein zuverlässiger Ibiza-Kontakt hinter der Kundenroute.'),('Concierge Firms','Direkt oder diskret','Client-facing oder im Hintergrund nach vereinbartem Workflow.'),('Hospitality','Verbundene Logistik','Transport und private Services rund um die Gästeanforderungen.'),('Internationale Teams','Schnelle Kommunikation','Klare WhatsApp- und E-Mail-Koordination vor und während des Aufenthalts.')],'overview_kicker':'Für professionelle Partner','overview_h2':'Kundenbeziehung schützen. Ausführung stärken.','overview_lead':'Der Kunde sollte eine nahtlose Reiseroute erleben, nicht die Komplexität verschiedener Ibiza-Supplier.','overview_p':'Wir unterstützen professionelle Partner mit lokaler Ausführung über Transport, Villen, Yachten, Aviation, Dining, Nightlife, Security, Staffing und individuelle Anforderungen. Die Kommunikationsstruktur wird passend zum Partner- und Kundenbrief vereinbart.','audiences':[('Luxury Travel Advisors','On-island Execution für private Kunden'),('Concierge Companies','Lokaler Multi-Service-Support'),('Hotels & Hospitality','Private Gästelogistik'),('PAs & Private Offices','Direkte operative Koordination')],'cta_h2':'Brauchen Sie einen Ibiza-Partner, den Sie direkt briefen können?','cta_p':'Stellen Sie Ihr Team vor oder senden Sie eine aktive Kundenanfrage. Wir klären Umfang, Verfügbarkeit und bevorzugte Kommunikationsstruktur.'}},
'ar':{
'office':{'title':'Private Office في إيبيزا | دعم PAs وFamily Offices | Ibiza VIP Move','desc':'Private Office في إيبيزا للضيوف الرئيسيين والعائلات والمساعدين الشخصيين وFamily Offices الذين يحتاجون إلى تنسيق محلي خاص لإقامة معقدة.','kicker':'Private Office · إيبيزا','h1':'مكتبك الخاص على الجزيرة.','lead':'للضيوف الرئيسيين والعائلات والمساعدين الشخصيين وFamily Offices الذين يحتاجون إلى جهة اتصال واحدة وسرية في إيبيزا خلف إقامة معقدة.','rail':[('Principals','إدارة خاصة','تنسيق رفيع المستوى حول الضيف الرئيسي والبرنامج المؤكد.'),('PAs & EAs','خط تشغيلي واحد','جهة اتصال محلية واحدة للجداول المتغيرة والخدمات المتعددة.'),('Family Offices','تفاصيل حسب الحاجة','طلبات خاصة بنطاق واضح وتواصل سري.'),('إقامات معقدة','من الوصول إلى المغادرة','النقل والفلل والوصول والطيران والأمن واللايف ستايل ضمن خطة واحدة.')],'overview_kicker':'بنية دعم للعملاء الخاصين','overview_h2':'إدارة أقل للموردين. تحكم أكبر.','overview_lead':'القيمة ليست حجزاً إضافياً، بل وجود مشغل محلي مسؤول يربط كل عناصر الإقامة المتحركة.','overview_p':'تدعم Ibiza VIP Move الضيوف الرئيسيين وممثليهم بتنسيق عملي على الجزيرة. يمكن أن تبدأ الخدمة قبل الوصول وتستمر طوال الإقامة وتتكيّف عندما تتغير الخطط.','audiences':[('الضيف الرئيسي والعائلة','دعم محلي خاص وعالي المستوى'),('المساعد الشخصي','خط واحد لتنفيذ البرنامج'),('Family Office','تنسيق موثوق في إيبيزا'),('Executive Assistant','تواصل تشغيلي سريع')],'cta_h2':'اجعل إيبيزا تحت جهة اتصال واحدة.','cta_p':'أرسل التواريخ وملف الضيوف ومستوى التنسيق المطلوب، وسنكمل التفاصيل بشكل خاص.'},
'partners':{'title':'B2B Partners إيبيزا | مشغل محلي للـ Luxury Travel | Ibiza VIP Move','desc':'شريك محلي في إيبيزا لمستشاري السفر الفاخر وشركات الكونسيرج والضيافة والمساعدين والفرق الدولية التي تحتاج إلى تنفيذ خاص على الجزيرة.','kicker':'B2B Partnerships · إيبيزا','h1':'مشغلك المحلي في إيبيزا.','lead':'تنفيذ محلي لمستشاري السفر الفاخر وشركات الكونسيرج وشركاء الضيافة والمساعدين وفرق العملاء الخاصين الدولية.','rail':[('Travel Advisors','تنفيذ محلي','جهة اتصال موثوقة في إيبيزا خلف برنامج العميل.'),('Concierge Firms','مباشر أو خلف الكواليس','دعم أمام العميل أو بشكل سري وفق آلية العمل المتفق عليها.'),('Hospitality','لوجستيات مترابطة','نقل وخدمات خاصة منسقة حول احتياجات الضيوف.'),('فرق دولية','تواصل سريع','تنسيق واضح عبر واتساب والبريد قبل الإقامة وأثناءها.')],'overview_kicker':'مصمم للشركاء المحترفين','overview_h2':'احمِ علاقة العميل. قوِّ التنفيذ.','overview_lead':'يجب أن يعيش العميل برنامجاً واحداً سلساً، لا تعقيد تنسيق موردين منفصلين في إيبيزا.','overview_p':'ندعم الشركاء المحترفين بالتنفيذ المحلي عبر النقل والفلل واليخوت والطيران والمطاعم والحياة الليلية والأمن والطاقم والطلبات المخصصة. ويتم الاتفاق على هيكل التواصل وفق الشريك وطلب العميل.','audiences':[('Luxury Travel Advisors','تنفيذ محلي للعملاء الخاصين'),('Concierge Companies','دعم محلي متعدد الخدمات'),('Hotels & Hospitality','لوجستيات خاصة للضيوف'),('PAs & Private Offices','تنسيق تشغيلي مباشر')],'cta_h2':'هل تحتاج إلى شريك في إيبيزا يمكنك إرسال الـ brief إليه مباشرة؟','cta_p':'عرّفنا على فريقك أو أرسل طلب عميل فعلياً. سنوضح النطاق والتوفر وطريقة التواصل المفضلة.'}}
}

COMMON={
'es':{'model':'Modelo operativo','model_h2':'Simple hacia fuera. Detallado detrás de escena.','model_p':'El partner o representante mantiene una línea clara mientras los servicios confirmados se coordinan alrededor del mismo itinerario.','steps':[('01 · Brief','Envía lo esencial.','Fechas, huéspedes, prioridades, servicios y estructura de comunicación preferida.'),('02 · Aclarar','Define el alcance.','Disponibilidad, horarios, requisitos operativos y términos aplicables se aclaran antes de confirmar.'),('03 · Alinear','Conecta el itinerario.','Los servicios confirmados se alinean alrededor del mismo brief.'),('04 · Support','Mantén capacidad de respuesta.','Si cambian los planes, los elementos afectados pueden revisarse por el mismo contacto de Ibiza.')],'start':'Iniciar private brief','email':'Email Partnerships'},
'fr':{'model':'Modèle opérationnel','model_h2':'Simple à l’extérieur. Détaillé en coulisses.','model_p':'Le partenaire ou représentant conserve une ligne de communication claire pendant que les services confirmés sont coordonnés autour du même itinéraire.','steps':[('01 · Brief','Partagez l’essentiel.','Dates, invités, priorités, services et structure de communication souhaitée.'),('02 · Clarifier','Définir le périmètre.','Disponibilité, horaires, exigences opérationnelles et conditions applicables sont clarifiés avant confirmation.'),('03 · Aligner','Connecter l’itinéraire.','Les services confirmés sont alignés autour du même brief.'),('04 · Support','Rester réactif.','Si le programme évolue, les éléments concernés peuvent être réévalués via le même contact Ibiza.')],'start':'Commencer le brief','email':'Email Partnerships'},
'de':{'model':'Operating Model','model_h2':'Nach außen einfach. Im Hintergrund detailliert.','model_p':'Partner oder Vertreter behalten eine klare Kommunikationslinie, während bestätigte Services rund um dieselbe Reiseroute koordiniert werden.','steps':[('01 · Brief','Das Wesentliche senden.','Daten, Gäste, Prioritäten, Services und gewünschte Kommunikationsstruktur.'),('02 · Klären','Umfang definieren.','Verfügbarkeit, Zeiten, operative Anforderungen und relevante Bedingungen werden vor Bestätigung geklärt.'),('03 · Abstimmen','Route verbinden.','Bestätigte Services werden um dasselbe Briefing herum abgestimmt.'),('04 · Support','Reaktionsfähig bleiben.','Wenn Pläne sich ändern, können betroffene Elemente über denselben Ibiza-Kontakt neu koordiniert werden.')],'start':'Private Anfrage starten','email':'Email Partnerships'},
'ar':{'model':'نموذج التشغيل','model_h2':'بسيط أمام العميل. دقيق خلف الكواليس.','model_p':'يحافظ الشريك أو الممثل على خط تواصل واضح بينما يتم تنسيق الخدمات المؤكدة حول البرنامج نفسه.','steps':[('01 · Brief','أرسل الأساسيات.','التواريخ والضيوف والأولويات والخدمات وطريقة التواصل المفضلة.'),('02 · توضيح','حدد النطاق.','يتم توضيح التوفر والمواعيد والمتطلبات التشغيلية والشروط ذات الصلة قبل التأكيد.'),('03 · تنسيق','اربط البرنامج.','يتم مواءمة الخدمات المؤكدة حول نفس الطلب.'),('04 · دعم','حافظ على المرونة.','إذا تغيرت الخطط يمكن مراجعة العناصر المتأثرة عبر جهة اتصال إيبيزا نفسها.')],'start':'بدء الطلب الخاص','email':'البريد للشراكات'}
}


def alt_tags(kind):
    tags=''.join(f'<link rel="alternate" hreflang="{lang}" href="{BASE}{path}">' for lang,path in PATHS[kind].items())
    return tags+f'<link rel="alternate" hreflang="x-default" href="{BASE}{PATHS[kind]["en"]}">'

def main(data,common):
    rail='<div class="ivm-b2b-rail">'+''.join(f'<article><span>{a}</span><strong>{b}</strong><small>{c}</small></article>' for a,b,c in data['rail'])+'</div>'
    audiences=''.join(f'<div><strong>{a}</strong><span>{b}</span></div>' for a,b in data['audiences'])
    steps=''.join(f'<article><span>{n}</span><h3>{h}</h3><p>{p}</p></article>' for n,h,p in common['steps'])
    return f'''<main><section class="page-hero"><div class="page-hero-media"><img src="/assets/images/private-office.jpg" alt="Ibiza VIP Move Private Office and B2B coordination" width="1800" height="1200" fetchpriority="high" decoding="async"></div><div><div class="kicker light">{data['kicker']}</div><h1>{data['h1']}</h1><p>{data['lead']}</p><a class="btn gold" href="{WA}">{common['start']}</a>{rail}</div></section><section class="ivm-b2b-overview"><div class="ivm-b2b-overview-inner"><div><div class="eyebrow">{data['overview_kicker']}</div><h2>{data['overview_h2']}</h2></div><div><p class="lead">{data['overview_lead']}</p><p>{data['overview_p']}</p><div class="ivm-b2b-audiences">{audiences}</div></div></div></section><section class="ivm-b2b-operating"><div class="ivm-b2b-operating-inner"><div class="ivm-b2b-operating-head"><div><div class="eyebrow">{common['model']}</div><h2>{common['model_h2']}</h2></div><p>{common['model_p']}</p></div><div class="ivm-b2b-steps">{steps}</div></div></section><section class="ivm-b2b-cta"><div class="ivm-b2b-cta-inner"><div><h2>{data['cta_h2']}</h2><p>{data['cta_p']}</p></div><div class="ivm-b2b-actions"><a class="btn dark" href="mailto:{EMAIL}">{common['email']}</a><a class="btn ghost" href="{WA}">WhatsApp 24/7</a></div></div></section></main>'''

def remove_webpage_schema(html):
    out=[];cursor=0
    for m in SCRIPT_RE.finditer(html):
        out.append(html[cursor:m.start()])
        try:o=json.loads(m.group(1))
        except Exception:o=None
        if not (isinstance(o,dict) and o.get('@type') in ('WebPage','AboutPage','ContactPage','CollectionPage')):out.append(m.group(0))
        cursor=m.end()
    out.append(html[cursor:]);return ''.join(out)

# Update English originals with reciprocal hreflang first.
for kind in PATHS:
    en=ROOT/PATHS[kind]['en'].strip('/')/'index.html'
    h=en.read_text(encoding='utf-8')
    h=re.sub(r'<link\s+rel="alternate"\s+hreflang="[^"]+"\s+href="[^"]+">','',h,flags=re.I)
    h=h.replace('</head>',alt_tags(kind)+'</head>',1)
    en.write_text(h,encoding='utf-8')

created=[]
for lang in ('es','fr','de','ar'):
    shell=ROOT/lang/'index.html'
    if not shell.exists():raise SystemExit(f'Localized shell missing: {lang}')
    shell_html=shell.read_text(encoding='utf-8')
    for kind in ('office','partners'):
        data=DATA[lang][kind];common=COMMON[lang];path=PATHS[kind][lang];canonical=BASE+path
        html=shell_html
        html=re.sub(r'<title>.*?</title>',f'<title>{escape(data["title"])}</title>',html,count=1,flags=re.I|re.S)
        html=re.sub(r'(<meta\s+name="description"\s+content=")[^"]*(")',lambda m:m.group(1)+escape(data['desc'])+m.group(2),html,count=1,flags=re.I)
        html=re.sub(r'(<link\s+rel="canonical"\s+href=")[^"]*(")',lambda m:m.group(1)+canonical+m.group(2),html,count=1,flags=re.I)
        html=re.sub(r'<link\s+rel="alternate"\s+hreflang="[^"]+"\s+href="[^"]+">','',html,flags=re.I)
        html=html.replace('</head>',alt_tags(kind)+'</head>',1)
        html=re.sub(r'(<meta\s+property="og:title"\s+content=")[^"]*(")',lambda m:m.group(1)+escape(data['title'])+m.group(2),html,count=1,flags=re.I)
        html=re.sub(r'(<meta\s+property="og:description"\s+content=")[^"]*(")',lambda m:m.group(1)+escape(data['desc'])+m.group(2),html,count=1,flags=re.I)
        html=re.sub(r'(<meta\s+property="og:url"\s+content=")[^"]*(")',lambda m:m.group(1)+canonical+m.group(2),html,count=1,flags=re.I)
        html=re.sub(r'<main\b[^>]*>.*?</main>',main(data,common),html,count=1,flags=re.I|re.S)
        body=re.search(r'<body(?:\s+class="([^"]*)")?>',html,re.I)
        if body:
            classes=(body.group(1) or '').split()
            if 'ivm-b2b-signature' not in classes:classes.append('ivm-b2b-signature')
            html=html[:body.start()]+'<body class="'+' '.join(classes)+'">'+html[body.end():]
        if STYLE not in html:html=html.replace('</head>',f'<link rel="stylesheet" href="{STYLE}"></head>',1)
        html=remove_webpage_schema(html)
        schema={'@context':'https://schema.org','@type':'WebPage','name':data['title'],'url':canonical,'description':data['desc'],'inLanguage':lang,'isPartOf':{'@type':'WebSite','name':'Ibiza VIP Move','url':BASE+'/'},'about':{'@id':BASE+'/#organization'}}
        html=html.replace('</head>',f'<script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head>',1)
        dest=ROOT/path.strip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(html,encoding='utf-8');created.append(path)

# Sitemap; Phase 41 will normalize full parity.
sitemap=ROOT/'sitemap.xml';s=sitemap.read_text(encoding='utf-8')
for path in created:
    url=BASE+path
    if url not in s:s=s.replace('</urlset>',f'<url><loc>{url}</loc></url></urlset>')
sitemap.write_text(s,encoding='utf-8')

# Validation.
for kind in PATHS:
    for lang,path in PATHS[kind].items():
        f=ROOT/path.strip('/')/'index.html'
        assert f.exists(),(kind,lang)
        h=f.read_text(encoding='utf-8')
        assert h.count('<h1')==1,(kind,lang,'h1')
        assert h.count('hreflang=')>=6,(kind,lang,'hreflang')
        assert BASE+path in h,(kind,lang,'canonical')
        if lang!='en':
            assert 'ivm-b2b-signature' in h,(kind,lang,'style')
            assert STYLE in h,(kind,lang,'css')
print(f'PASS: Phase 51 multilingual Private Office + Partners created — {len(created)} new pages, two five-language clusters')
